AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  awslambda-ordersapi
  Sample SAM Template for awslambda-ordersapi

Globals:
  Function: # anywhere you have a function they will have these global properties
    Runtime: java17
    Architectures:
      - x86_64
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables: #!Ref <resourceName> is a special operator the SAM uses to get the reference of the resource created. Like:
        #Orders_table_<random_value>. We won't know the value so !Ref will do this
        ORDERS_TABLE: !Ref OrdersTable # will get the final name


Resources:
  OrdersTable: # Cloud formation stack will create this resource
    Type: AWS::Serverless::SimpleTable # Type of resource we'll use
    Properties:
      PrimaryKey:
        Name: id #id is our primary key i.e partition key
        Type: Number
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: awslambda-ordersapi
      Handler: com.kushal.aws.lambda.apis.CreateOrderLambda::createOrder
      Policies:
        - DynamoDBCrudPolicy: # If table name not mentioned, it'll have permission to perform operations on all table
            TableName: !Ref OrdersTable
      Events: # to configure anything any resource as a trigger
        OrderEvents: # resource name
          Type: Api
          Properties:
            Path: /orders
            Method: POST

  ReadOrdersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: awslambda-ordersapi
      Handler: com.kushal.aws.lambda.apis.ReadOrdersLambda::getOrders
      Policies:
        - DynamoDBReadPolicy: # If table name not mentioned, it'll have permission to perform operations on all table
            TableName: !Ref OrdersTable
      Events: # to configure anything any resource as a trigger
        OrderEvents: # resource name
          Type: Api
          Properties:
            Path: /orders
            Method: GET


