AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  awslambda-ordersapi
  Sample SAM Template for awslambda-ordersapi

Resources:
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: awslambda-ordersapi
      Handler: com.kushal.aws.lambda.apis.CreateOrderLambda::createOrder
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Events: # to configure anything any resource as a trigger
        OrderEvents: # resource name
          Type: Api
          Properties:
            Path: /orders
            Method: POST

  ReadOrdersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: awslambda-ordersapi
      Handler: com.kushal.aws.lambda.apis.ReadOrdersLambda::getOrders
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Events: # to configure anything any resource as a trigger
        OrderEvents: # resource name
          Type: Api
          Properties:
            Path: /orders
            Method: GET


