AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  firstlambda

  Sample SAM Template for firstlambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      #package.className::methodName. After changes run sam build and if local run -> sam local invoke ....
#      Handler: helloworld.App::hello #package.className::methodName
#      Handler: com.kushal.aws.lambda.DataTypes::getNumber
#      Handler: com.kushal.aws.lambda.DataTypes::isGreaterThan100
#      Handler: com.kushal.aws.lambda.DataTypes::getScores
#      Handler: com.kushal.aws.lambda.DataTypes::getScoreGreaterThan90
#      Handler: com.kushal.aws.lambda.DataTypes::getStudentScores
#      Handler: com.kushal.aws.lambda.DataTypes::getClinicals
#      Handler: com.kushal.aws.lambda.DataTypes::getOutputInLowerCase
      Handler: com.kushal.aws.lambda.DataTypes::playWithAWSLambdaContextObject
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
